AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  entity-extractor-app

  Sample SAM Template for entity-extractor-app
Parameters:
  ApiStage:
    Description: The name of the stage for the API (e.g. Dev/Prod/Test)
    Default: Prod

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Resources:
  EntityExtractorFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: entity_extractor/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        EntityExtractor:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /extract-entities
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  EntityExtractorApi:
    Description: "API Gateway endpoint URL for Prod stage for ExtractEntities function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/${ApiStage}/extract-entities"
  EntityExtractorFunction:
    Description: "ExtractEntities Lambda Function ARN"
    Value: !GetAtt EntityExtractorFunction.Arn
  EntityExtractorFunctionIamRole:
    Description: "Implicit IAM Role created for ExtractEntities function"
    Value: !GetAtt EntityExtractorFunctionRole.Arn
